= Установка



== Установка Nim

Nim уже имеет готовые дистрибутивы для всех трёх основных операционных систем, и есть несколько вариантов установки Nim.

Вы можете следовать https://nim-lang.org/install.html[официальной процедуре установки] чтобы установить последнюю стабильную версию, или вы можете использовать инструмент под названием https://github.com/nim-lang/choosenim[choosenim], который позволяет легко переключаться между стабильной и последней версией разработки, если вы хотите использовать последние функции и исправления.
н
Какой бы способ вы ни выбрали, просто следуйте процедуре установки, объясненной на каждом из этих ресурсов, и Nim будет установлен.
Мы проверим успешность установки в следующем разделе.   

Если вы используете Linux, существует высокая вероятность, что ваш дистрибутив имеет Nim в менеджере пакетов.
Если вы устанавливаете его таким образом, убедитесь, что это последняя версия (см. сайт для информации о последней версии), иначе установите через один из двух методов, упомянутых выше.

В этом руководстве мы будем использовать стабильную версию.
Изначально это руководство было написано для Nim 0.19 (выпущена в сентябре 2018 года), и оно должно работать с любой более новой версией, включая Nim 1.x и Nim 2.x.

== Установка дополнительных инструментов

Вы можете писать код на Nim в любом текстовом редакторе, а затем компилировать и запускать его из терминала.
Если вы хотите подсветку синтаксиса и автозавершение кода, существуют плагины для популярных редакторов кода, которые предоставляют данные функции.

Большинство пользователей Nim предпочитают редактор https://code.visualstudio.com/[VS Code] с https://marketplace.visualstudio.com/items?itemName=NimLang.nimlang[расширением Nim], которое предоставляет подсветку синтаксиса и автозавершение кода, и https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner[расширением Code Runner] для быстрой компиляции и запуска.

Автор лично использует https://neovim.io/[NeoVim] редактор с https://github.com/alaviss/nim.nvim[этим плагином], который предоставляет дополнительные функции, такие как подсветка синтаксиса и автозавершение кода.

Если вы используете другие редакторы кода, посмотрите https://github.com/nim-lang/Nim/wiki/Editor-Support[вики] для доступной поддержки редакторов.

== Проверка установки

Чтобы проверить успешность установки, мы напишем программу, которая традиционно используется в качестве вводного примера: https://en.wikipedia.org/wiki/%22Hello,_World!%22_program[Hello World].

Печать (в смысле: отображать на экране; не на бумаге с помощью принтера) фразу `Hello World!` на Nim просто и не требует никакого шаблонного кода.

В новом текстовом файле под названием, например, `helloworld.nim` нужно написать всего одну строку кода:

[source]
.helloworld.nim
----
include::code/helloworld.nim[]
----

NOTE: Фраза, которую вы хотите напечатать, должна следовать за командой `echo` и быть заключена в двойные кавычки (`"`).

Прежде нам нужно скомпилировать нашу программу, а затем запустить её, чтобы проверить, работает ли она как ожидается.

Откройте ваш терминал в той же директории, где находится ваш файл (на Linux вы можете открыть "Открыть терминал здесь", если вы щёлкните правой кнопкой мыши по директории в вашем файловом менеджере, на Windows вы должны использовать Shift + щёлкнуть правой кнопкой мыши, чтобы получить опцию меню для открытия командной строки).

Мы компилируем нашу программу, набирая в терминале:
[source, terminal]
----
nim c helloworld.nim
----

После успешной компиляции мы можем запустить нашу программу.
На Linux мы можем запустить нашу программу, набрав `./helloworld` в терминале, а на Windows мы делаем это, набрав `helloworld.exe`.

также есть возможность скомпилировать и запустить программу одной командой.
Нужно набрать:
[source, terminal]
----
nim c -r helloworld.nim
----

NOTE: `c` говорит Nim скомпилировать файл, а `-r` говорит сразу же его запустить. Чтобы увидеть все опции компилятора, наберите `nim --help` в вашем терминале.

Если вы используете VSCode с упомянутым ранее расширением Code Runner, вам просто нужно нажать `Ctrl+Alt+N`, и ваш файл будет скомпилирован и запущен.

Не важно, какой из этих способов вы выберете для запуска вашей программы, после короткого момента в окне вывода (или в вашем терминале) вы должны увидеть:
[source, output]
----
Hello World!
----

Поздравляем, вы успешно запустили свою первую программу на Nim!

Теперь вы знаете, как печатать текст на экране (используя команду `echo`), компилировать программу (набирая `nim c programName.nim` в терминале) и запускать её (различными способами).

Мы можем теперь начать изучать основные элементы, которые помогут нам писать простые программы на Nim.
