= Основные типы данных



== Целые числа

Как видно из предыдущей главы, целые числа - это числа, которые записываются без дробной части и без десятичной точки.

Например: `32`, `-174`, `0`, `10_000_000` являются целыми числами.
Обратите внимание, что мы можем использовать `_` как разделитель тысяч, чтобы сделать большие числа более читаемыми (легче понять, что речь идет о 10 миллионов, когда они записаны как 10_000_000, а не как 10000000).

Обычные математические операторы -- сложение (`+`), вычитание (`-`), умножение (`*`) и деление (`/`) -- работают так, как можно было бы ожидать.
Первые три операции всегда производят целые числа, в то время как деление двух целых чисел всегда дает число с плавающей точкой (число с десятичной точкой) в результате, даже если два числа могут быть разделены без остатка.

Деление целых чисел (деление, при котором дробная часть отбрасывается) можно выполнить с помощью оператора `div`.
Оператор `mod` используется, если вас интересует остаток от деления целых чисел (модуль).
Результат этих двух операций всегда является целым числом.

[source]
.integers.nim
----
include::{source-dir}/integers.nim[]
----
<1> Команда `echo` напечатает на экране всё, что следует за ней, разделённое запятыми. В данном случае она сначала печатает строку ``a + b = ``, а затем, в той же строке, печатает результат выражения `a + b`.

Мы можем скомпилировать и запустить приведённый выше код, и вывод должен быть следующим:
[source, output]
----
a + b = 15
a - b = 7
a * b = 44
a / b = 2.75
a div b = 2
a mod b = 3
----




== Числа с плавающей точкой

Числа с плавающей точкой, или просто float, являются https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D0%BB%D0%BE_%D1%81_%D0%BF%D0%BB%D0%B0%D0%B2%D0%B0%D1%8E%D1%89%D0%B5%D0%B9_%D0%B7%D0%B0%D0%BF%D1%8F%D1%82%D0%BE%D0%B9[приблизительным представлением] действительных чисел.

Например: `2.73`, `-3.14`, `5.0`, `4e7` являются числами с плавающей точкой.
Обратите внимание, что мы можем использовать научную нотацию для больших чисел с плавающей точкой, где число после `e` является показателем степени.
В этом примере, `4e7` - это запись, представляющая `4 * 10^7`.

Мы можем выполнять математические операции с числами с плавающей точкой так же, как и с целыми числами.
Операторы `div` и `mod` не определены для чисел с плавающей точкой.

[source]
.floats.nim
----
include::{source-dir}/floats.nim[]
----

[source, output]
----
c + d = 9.0  <1>
c - d = 4.5
c * d = 15.1875
c / d = 3.0  <1>
----
<1> Обратите внимание, что в примерах сложения и деления, даже если мы получаем число без десятичной части, результат всё равно является числом с плавающей точкой.

Последовательность выполнения математических операций соответствует ожидаемой: умножение и деление имеют более высокий приоритет, чем сложение и вычитание.

[source]
----
echo 2 + 3 * 4
echo 24 - 8 / 4
----

[source, output]
----
14
22.0
----




=== Преобразование float и int

Математические операции между переменными разных числовых типов невозможны в Nim и приведут к ошибке:
[source]
----
let
  e = 5
  f = 23.456

echo e + f   # error
----

Значения переменных необходимо преобразовать к одному типу.
Преобразование достаточно простое: для преобразования в целое число используется функция `int`, а для преобразования в число с плавающей точкой - функция `float`.
[source]
----
let
  e = 5
  f = 23.987

echo float(e)      <1>
echo int(f)        <2>

echo float(e) + f  <3>
echo e + int(f)    <4>
----
<1> Печать `float` версии `int` числа `e`. (`e` остаётся `int`)
<2> Печать `int` версии `float` числа `f`.
<3> Оба операнда являются числами с плавающей точкой и могут быть сложены.
<4> Оба операнда являются целыми числами и могут быть сложены.
[source, output]
----
5.0
23
28.987
28
----

NOTE: Когда мы используем функцию `int` для преобразования числа с плавающей точкой в целое, округление не производится.
Число просто отбрасывает десятичную часть. +
Для выполнения округления необходимо вызвать другую функцию, но для этого нужно знать немного больше о том, как использовать Nim.


== Символы

Тип `char` используется для представления одного https://ru.wikipedia.org/wiki/ASCII[ASCII] символа.

Символы записываются между двумя одинарными кавычками (`'`).
Символы могут быть буквами, символами или одиночными цифрами.
Несколько цифр или несколько букв вызовут ошибку.
[source]
----
let
  h = 'z'
  i = '+'
  j = '2'
  k = '35' # error
  l = 'xy' # error
----




== Строки

Строки могут быть описаны как последовательность символов.
Их содержимое записывается между двумя двойными кавычками (`"`).

Мы можем думать о строках как о словах, но они могут содержать более одного слова, некоторые символы или цифры.

[source]
.strings.nim
----
include::{source-dir}/strings.nim[]
----
<1> Пустая строка.
<2> Это не число (int). Оно находится внутри двойных кавычек, поэтому является строкой.
<3> Даже если это только один символ, это не char, потому что он заключен внутри двойных кавычек.


=== Специальные символы в строках

Есди мы попытаемся напечатать следующую строку:
[source]
----
echo "some\nim\tips"
----
результат может удивить нас:
[source, output]
----
some
im	ips
----

Это происходит потому, что есть несколько символов, которые имеют специальное значение.
Они используются путем добавления перед ними символа экранирования `\`.

* `\n` это символ новой строки
* `\t` это символ табуляции
* `\\` это обратная косая черта (так как одна `\` используется как символ экранирования)

Если мы хотим напечатать вышеуказанный пример так, как он был написан, у нас есть два варианта:
* Используйте `\\` вместо `\` для печати обратных косых черт, или
* Используйте сырые строки, которые имеют синтаксис `r"..."` (помещая букву `r` сразу перед первой кавычкой), в которых нет символов экранирования и специальных значений: всё печатается как есть.

[source]
----
echo "some\\nim\\tips"
echo r"some\nim\tips"
----

[source, output]
----
some\nim\tips
some\nim\tips
----

Есть и другие специальные символы, помимо перечисленных выше и их можно найти в https://nim-lang.org/docs/manual.html#lexical-analysis-string-literals[руководстве по Nim].



=== Конкатенация строк

Строки в Nim изменяемы, что означает, что их содержимое может изменяться.
С помощью функции `add` мы можем добавить (присоединить) либо другую строку, либо символ к существующей строке.
Если мы не хотим изменять исходную строку, мы также можем конкатенировать (соединять вместе) строки с помощью оператора `&`, который возвращает новую строку.

[source]
.stringConcat.nim
----
include::{source-dir}/stringConcat.nim[]
----
<1> Если мы планируем изменять строки, они должны быть объявлены как `var`.
<2> Добавление другой строки изменяет существующую строку `p` на месте, меняя её значение.
<3> Мы также можем добавить символ к строке.
<4> Конкатенация двух строк создаёт новую строку, не изменяя исходные строки.

[source, output]
----
p is now: abcdef
q is now: xyz
concat: abcdefxyz
p is still: abcdef
q is still: xyz
----






== Булевы значения

Булево значение (или просто `bool`) может иметь только два значения: `true` или `false`.
Булевы значения обычно используются для управления потоком выполнения (см. <<Поток управления, следующая глава>>), и они часто являются результатом операторов сравнения.

Обычное соглашение по именованию булевых переменных — писать их как простые вопросы да/нет (true/false), например, `isEmpty`, `isFinished`, `isMoving` и т.д.

=== Операторы сравнения

Операторы сравнения проверяют отношение между двумя сущностями, которые должны быть сравнимы.

Чтобы сравнить два значения и определить, равны ли они, используются `==` (два знака равенства).
Не путайте это с `=`, который используется для присваивания, как мы видели ранее.

Тут все операторы сравнения для целых чисел:

[source]
.relationalOperators.nim
----
include::{source-dir}/relationalOperators.nim[lines=1..11]
----

[source, output]
----
g is greater than h: false
g is smaller than h: true
g is equal to h: false
g is not equal to h: true
g is greater or equal to h: false
g is smaller or equal to h: true
----


Мы также можем использовать эти операторы для сравнения символов (`char`) и строк (`string`):

[source]
.relationalOperators.nim
----
include::{source-dir}/relationalOperators.nim[lines=13..30]
----
<1> Все заглавные буквы идут перед строчными буквами.
<2> Сравнение строк происходит посимвольно. Первые три символа одинаковы, и символ `b` меньше символа `z`.
<3> Длина строки не влияет на сравнение, если символы не совпадают.
<4> Короткая строка меньше длинной строки.

[source, output]
----
true
false
true
true
true
----




=== Логические операторы

Логические операторы используются для проверки истинности выражения, состоящего из одного или нескольких булевых значений.

* Логическое `and` возвращает `true` только если оба члена равны `true`
* Логическое `or` возвращает `true`, если хотя бы один член равен `true`
* Логическое `xor` возвращает `true`, если один член равен `true`, но другой нет
* Логическое `not` отрицает истинность своего члена: меняет `true` на `false`, и наоборот (это единственный логический оператор, который принимает только один операнд)

[source]
.logicalOperators.nim
----
include::{source-dir}/logicalOperators.nim[]
----

[source, output]
----
T and T: true
T and F: false
F and F: false
---
T or T: true
T or F: true
F or F: false
---
T xor T: false
T xor F: true
F xor F: false
---
not T: false
not F: true
----


Операторы сравнения и логические операторы могут быть использованы вместе для создания более сложных выражений.

Например: `(5 < 7) and (11 + 9 == 32 - 2*6)` станет `true and (20 == 20)`, что станет `true and true`, и в конце это даст окончательный результат `true`.



== Заключение

Эта глава была самой длинной в этом Туториале, и мы охватили много материала.
Не торопитесь, чтобы пройтись по каждому типу данных и поэкспериментировать с тем, что вы можете сделать с каждым из них.

Типы могут показаться ограничением на первый взгляд, но они позволяют компилятору Nim как ускорить ваш код, так и убедиться, что вы не делаете что-то неправильно по ошибке — это особенно полезно в больших кодовых базах.

Теперь вы знаете основные типы данных и несколько операций над ними, чего должно быть достаточно, чтобы выполнять простые вычисления в Nim.
Проверьте свои знания, выполнив следующие упражнения.




== Упражнения

1. Создайте неизменяемую переменную, содержащую ваш возраст (в годах). Выведите ваш возраст в днях. (1 год = 365 дней)
2. Проверьте, делится ли ваш возраст на 3 без остатка. (Подсказка: используйте `mod`)
3. Создайте неизменяемую переменную, содержащую ваш рост в сантиметрах. Выведите ваш рост в дюймах. (1 дюйм = 2.54 см)
4. Труба имеет диаметр 3/8 дюйма. Выразите диаметр в сантиметрах.
5. Создайте неизменяемую переменную, содержащую ваше имя, и еще одну переменную, содержащую вашу фамилию. Создайте переменную `fullName`, объединив предыдущие две переменные. Не забудьте поставить пробел между ними. Выведите ваше полное имя.
6. Алиса зарабатывает $400 каждые 15 дней. Боб зарабатывает $3.14 в час и работает 8 часов в день, 7 дней в неделю. Через 30 дней Алиса заработала больше, чем Боб? (Подсказка: используйте операторы сравнения)
