= Поток управления


До сих пор в наших программах каждая строка кода выполнялась в тот или иной момент.
Операторы потока управления позволяют нам иметь части кода, которые будут выполняться только если удовлетворяется некоторое булево условие.

Если мы представим нашу программу как дорогу, то поток управления можно представить как различные развилки, и мы выбираем наш путь в зависимости от некоторого условия.
Например, мы купим яйца только _если_ их цена меньше некоторого значения.
Или, _если_ идет дождь, мы возьмем зонт, _иначе_ (_иначе_) мы возьмем солнечные очки.

Написаныные в https://en.wikipedia.org/wiki/Pseudocode[pseudocode], эти два примера будут выглядеть примерно так:

[source]
----
if eggPrice < wantedPrice:
  buyEggs

if isRaining:
  bring umbrella
else:
  bring sunglasses
----

Синтаксис Nim очень похож, как вы увидите ниже.





== Оператор If 

Оператор `if`, как показано выше, является самым простым способом разветвления нашей программы.

Синтаксис Nim для написания оператора `if` выглядит следующим образом:

[source]
----
if <condition>:     <1>
  <indented block>  <2>
----

<1> `condition` должно быть булевого типа: либо булевая переменная, либо сравнение и/или логическое выражение.
<2> Все строки, следующие за строкой `if`, которые отступлены на два пробела, составляют один блок и будут выполнены только если условие `true`.

Операторы if могут быть вложенными, т.е. внутри одного блока if может находиться другой оператор if.

[source]
.if.nim
----
include::{source-dir}/if.nim[]
----
<1> Первое условие истинно, второе ложно -- внутренний `echo` не выполняется.
<2> Оба условия истинны и обе строки печатаются.
<3> Первое условие ложно -- все строки внутри блока будут пропущены, ничего не напечатается.
<4> Использование логического `and` внутри оператора `if`.

[source, output]
----
a is smaller than b
b is smaller than c
not only that, b is *much* smaller than c
----



=== Else

Else следует за if-блоком и позволяет нам иметь ветку кода, которая будет выполнена, когда условие в операторе if не истинно.

[source]
.else.nim
----
include::{source-dir}/else.nim[]
----

[source, output]
----
d is a large number
e is a small number
----

NOTE: Если вы хотите выполнить блок, если условие `false`, вы можете просто отрицать условие с помощью оператора `not`.




=== Elif

Elif это сокращение для "else if", и позволяет нам объединять несколько операторов if.

Программа тестирует каждое условие до тех пор, пока не найдет истинное.
После этого все последующие условия игнорируются.

[source]
.elif.nim
----
include::{source-dir}/elif.nim[]
----

[source, output]
----
f is larger than 1000
g is smaller than 1000
----

NOTE: В случае `g`, даже если `g` удовлетворяет всем трем условиям, выполняется только первая ветка, автоматически пропуская все остальные ветки.




== Case

Оператор case является другим способом выбрать один из нескольких возможных путей, аналогично оператору if с несколькими ``elif``.
Оператор `case`, однако, не принимает несколько булевых условий, а принимает любое значение с различными состояниями и путь для каждого возможного значения.

Код, написанный в блоке if-elif выглядит так:

[source]
----
if x == 5:
  echo "Five!"
elif x == 7:
  echo "Seven!"
elif x == 10:
  echo "Ten!"
else:
  echo "unknown number"
----
может быть написан с использованием оператора case следующим образом:

[source]
----
case x
of 5:
  echo "Five!"
of 7:
  echo "Seven!"
of 10:
  echo "Ten!"
else:
  echo "unknown number"
----

В отличии от оператора if, оператор case должен покрывать _все_ возможные случаи.
Если вы не заинтересованы в некоторых из этих случаев, можно использовать `else: discard`.

[source]
.case.nim
----
include::{source-dir}/case.nim[]
----
<1> Даже если мы заинтересованы только в трех значениях `h`, мы должны включить эту строку, чтобы покрыть все остальные возможные случаи (все другие символы). Без нее код не скомпилируется.

[source, output]
----
You've chosen y
----



Мы также можем использовать несколько значений для каждой ветки, если для более чем одного значения должно произойти одно и то же действие.
[source]
.multipleCase.nim
----
include::{source-dir}/multipleCase.nim[]
----

[source, output]
----
i is odd
----
