= Циклы



Циклы являются еще одной конструкцией управления потоком, которая позволяет нам выполнять некоторые части кода несколько раз.

В этом разделе мы познакомимся с двумя видами циклов:

* Цикл for: Запускается известное количество раз
* Цикл while: Запускается до тех пор, пока некоторое условие истинно


== Цикл For

Синтаксис цикла for выглядит следующим образом:
[source]
----
for <переменная_цикла> in <итерируемый_объект>:
  <тело_цикла>
----

Традиционно, `i` часто используется в качестве имени `переменная_цикла`, но может быть использовано любое другое имя.
Эта переменная будет доступна только внутри цикла.
После завершения цикла значение переменной отбрасывается.

`Итерируемый_объект` (или просто `итерируемый`) - это объект, содержащий несколько значений, по которым мы хотим пройтись в цикле.
Как в Основных типах данных было упомянуто ранее, строки это итерируемый объект.
(Больше итерируемых типов будут представлены в <<Контейнеры, следующая глава>>.)

Все строки в `теле_цикла` выполняются при каждой итерации цикла, что позволяет эффективно писать повторяющиеся части кода.

{nbsp}

Если мы хотим итерироваться по диапазону (целых) чисел в Nim, синтаксис для `итерируемого` это `start .. finish`, где `start` и `finish` это числа.
Это будет итерироваться по всем числам между `start` и `finish`, включая оба `start` и `finish`.
Для итерируемого по умолчанию диапазона, `start` должен быть меньше чем `finish`.

Есди мы хотим итерироваться _до_ числа (не включая его), мы можем использовать `..<`:

[source]
.for1.nim
----
include::{source-dir}/for1.nim[]
----
<1> Итерируя по диапазону чисел с помощью `..` -- оба конца будут включены в диапазон.
<2> Итерируя по тому же диапазону с помощью `..<` -- итерирование происходит до верхней границы, не включая её.

[source, output]
----
5
6
7
8
9

5
6
7
8
----



Если мы хотим итерироваться по диапазону чисел с шагом, отличным от одного, используется `countup`. С помощью `countup` мы определяем начальное значение, конечное значение (включенное в диапазон) и размер шага.

[source]
.for2.nim
----
include::{source-dir}/for2.nim[lines=1..2]
----
<1> Счётчик от нуля до 16 с шагом 4. Конечное значение (16) включено в диапазон.

[source, output]
----
0
4
8
12
16
----


Чтобы итерироваться по диапазону чисел, где `start` больше чем `finish`, используется похожая функция под названием `countdown`. 
Даже если мы считаем вниз, размер шага должен быть положительным.

[source]
.for2.nim
----
include::{source-dir}/for2.nim[lines=5..12]
----
<1> Чтобы итерироваться от большего к меньшему числу, мы должны использовать `countdown` (оператор `..` может быть использован только когда начальное значение меньше конечного).
<2> Даже при обратном отсчете размер шага должен быть положительным.

[source, output]
----
4
3
2
1
0

-3
-5
-7
-9
----


Поскольку строка является итерируемым объектом, мы можем использовать цикл for, чтобы итерироваться по каждому символу строки (такой вид итерации иногда называют _for-each_ циклом).

[source]
.for3.nim
----
include::{source-dir}/for3.nim[lines=1..4]
----

[source, output]
----
a
l
p
h
a
b
e
t
----


Если нам также нужно иметь счетчик итераций (начинающийся с нуля), мы можем достичь этого, используя синтаксис `for <переменнаяСчетчика>, <переменнаяЦикла> in <итерируемый>:`.
Ланный способ очень практичекие если вы желаеье итерировать один iterable, и одновременно получать доступ к другому iterable на том же смещении.

[source]
.for3.nim
----
include::{source-dir}/for3.nim[lines=7..9]
----

[source, output]
----
letter 0 is: a
letter 1 is: l
letter 2 is: p
letter 3 is: h
letter 4 is: a
letter 5 is: b
letter 6 is: e
letter 7 is: t
----




== Цикл While

Цикл While похож на условный оператор if, но он продолжает выполнять свой блок кода до тех пор, пока условие остается истинным.
Они используются, когда мы заранее не знаем, сколько раз цикл будет выполняться.

Мы должны убедиться, что цикл в какой-то момент завершится и не станет https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BA%D0%BE%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9_%D1%86%D0%B8%D0%BA%D0%BB[бесконечным циклом].

[source]
.while.nim
----
include::{source-dir}/while.nim[]
----
<1> Это условие будет проверяться каждый раз перед входом в новый цикл и выполнением кода внутри него.
<2> `inc` используется для увеличения `a` на единицу. Это то же самое, что и `a = a + 1` или `a += 1`.

[source, output]
----
a is: 1
a is: 2
a is: 3
final value of a: 4
----




== Break и continue

Оператор `break` используется для преждевременного выхода из цикла, обычно если какое-то условие выполняется.

В следующем примере, если бы не было условия `if` с `break`, цикл продолжился бы и выводил бы значения до тех пор, пока `i` не станет 1000.
С оператором `break`, когда `i` становится 3, мы немедленно выходим из цикла (до вывода значения `i`).

[source]
.break.nim
----
include::{source-dir}/break.nim[]
----

[source, output]
----
1
2
----

{nbsp}

Оператор `continue` начинает следующую итерацию цикла немедленно, не выполняя оставшиеся строки текущей итерации.
Обратите внимание, что 3 и 6 отсутствуют в выводе следующего кода:

[source]
.continue.nim
----
include::{source-dir}/continue.nim[]
----

[source, output]
----
1
2
4
5
7
8
----




== Упражнения

1. https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%B7%D0%B0_%D0%9A%D0%BE%D0%BB%D0%BB%D0%B0%D1%82%D1%86%D0%B0[Гипотеза Коллатца] это популярная математическая задача с простыми правилами. Сначала выберите число. Если оно нечетное, умножьте его на три и прибавьте один; если четное, разделите его на два. Повторяйте эту процедуру до тех пор, пока не получите единицу. Например: 5 -> нечетное -> 3*5 + 1 = 16 -> четное -> 16 / 2 = 8 -> четное -> 4 -> 2 -> 1 -> конец! +
Выберите целое число (как изменяемую переменную) и создайте цикл, который будет печатать каждый шаг гипотезы Коллатца. (Подсказка: используйте `div` для деления)

2. Создайте неизменяемую переменную, содержащую ваше полное имя. Напишите цикл for, который будет итерировать по этой строке и печатать только гласные (a, e, i, o, u). (Подсказка: используйте оператор `case` с несколькими значениями ветви)

3. https://ru.wikipedia.org/wiki/Fizz_buzz[Fizz buzz] это детская игра, иногда используемая для проверки базовых знаний программирования. Мы считаем числа от одного вверх. Если число делится на 3, замените его на _fizz_, если оно делится на 5, замените его на _buzz_, а если число делится на 15 (оба 3 и 5), замените его на _fizzbuzz_. Первые несколько раундов будут выглядеть так: 1, 2, fizz, 4, buzz, fizz, 7, ... +
Создайте программу, которая будет печатать первые 30 раундов Fizz buzz. (Подсказка: обратите внимание на порядок проверок делимости)

4. В предыдущих упражнениях вы конвертировали дюймы в сантиметры и наоборот. Создайте таблицу конвертации с несколькими значениями. Например, таблица может выглядеть так: +
----
in	| cm
----------------
1	| 2.54
4	| 10.16
7	| 17.78
10	| 25.4
13	| 33.02
16	| 40.64
19	| 48.26
----
