= Модули


До сих пор мы использовали функциональность, которая доступна по умолчанию каждый раз, когда мы запускаем новый файл Nim.
Это можно расширить с помощью модулей, которые предоставляют больше функциональности по некоторым конкретным темам.

Некоторые из наиболее часто используемых модулей Nim:

* `strutils`: дополнительная функциональность при работе со строками
* `sequtils`: дополнительная функциональность для последовательностей
* `math`: математические функции (логарифмы, квадратные корни, ...), тригонометрия (sin, cos, ...)
* `times`: измерение и работа со временем

Но их гораздо больше, как в так называемой https://nim-lang.org/docs/lib.html[стандартной библиотеке], так и в https://nimble.directory/[менеджере пакетов nimble].




== Импортирование модуля

Если мы хотим импортировать модуль и всю его функциональность, все, что нам нужно сделать, это поместить `import <moduleName>` в наш файл.
Это обычно делается вверху файла, чтобы мы могли легко видеть, что использует наш код.

[source]
.stringutils.nim
----
include::{source-dir}/stringutils.nim[]
----
<1> Импортируем https://nim-lang.org/docs/strutils.html[strutils].
<2> Используем `split` из модуля `strutils`. Он разбивает строку на последовательность слов.
<3> `toUpperAscii` преобразует все ASCII буквы в верхний регистр.
<4> `repeat` также из модуля `strutils`, и он повторяет либо символ, либо всю строку указанное количество раз.

[source, output]
----
@["My", "string", "with", "whitespace."]
MY STRING WITH WHITESPACE.
!!!!!
----

NOTE: Для пользователей, приходящих из других языков программирования (особенно Python), способ импорта в Nim может показаться "неправильным". Если это так, рекомендуется прочитать https://narimiran.github.io/2019/07/01/nim-import.html[это].

{nbsp}


[source]
.maths.nim
----
include::{source-dir}/maths.nim[]
----
<1> Импортируем https://nim-lang.org/docs/math.html[math].
<2> Преобразуем градусы в радианы с помощью `degToRad`.
<3> `sin` принимает радианы. Мы округляем (также из модуля `math`) результат до максимум 2 знаков после запятой. (В противном случае результат был бы: 0.4999999999999999)
<4> Модуль math также имеет оператор `^` для вычисления степеней числа.

[source, output]
----
0.5235987755982988
0.5
32
----




== Создание собственных модулей

Спустя время у нас будет достаточно кода в проекте, что имеет смысл разделить его на части, каждая из которых делает определённую вещь.
Если вы создадите два файла рядом в папке, назовём их `firstFile.nim` и `secondFile.nim`, вы можете импортировать один из другого как модуль:

[source]
.firstFile.nim
----
proc plus*(a, b: int): int = <1>
  return a + b

proc minus(a, b: int): int = <2>
  return a - b
----
<1> Обратите внимание, как процедура `plus` теперь имеет звёздочку (`*`) после её имени, это говорит Nim, что другой файл, импортирующий этот файл, сможет использовать эту процедуру.
<2> В противоположность этому, эта процедура не будет видна при импорте этого файла.

[source]
.secondFile.nim
----
import firstFile          <1>

echo plus(5, 10)          <2>
echo minus(10, 5) # error <3>
----
<1> Тут мы импортируем `firstFile.nim`. Нам не нужно добавлять расширение `.nim`.
<2> Это будет работать нормально и выведет `15`, так как процедура объявлена в `firstFile` и доступна нам.
<3> Однако это вызовет ошибку, так как процедура `minus` не видна, так как у неё нет звёздочки после имени.


В случае, если у вас больше двух файлов, вы можете организовать их в подкаталоги (или более одного подкаталога).
Со следующей структурой каталогов:

[source, output]
----
.
├── myOtherSubdir
│   ├── fifthFile.nim
│   └── fourthFile.nim
├── mySubdir
│   └── thirdFile.nim
├── firstFile.nim
└── secondFile.nim
----

Если вы хотите импортировать все файлы в вашем `secondFile.nim`, вот как вы это сделаете:

[source]
.secondFile.nim
----
import firstFile
import mySubdir/thirdFile
import myOtherSubdir / [fourthFile, fifthFile]
----
