= Взаемодействие с пользовательским вводом


Использование того, что мы уже представили до сих пор (базовые типы данных и контейнеры, управление потоком, циклы) позволяет нам создавать довольно много простых программ.

В этой главе мы научимся делать наши программы более интерактивными.
Для этого нам нужна возможность читать данные из файла или запрашивать ввод от пользователя.




== Чтение из файла

Например мы имеем текстовый файл под названием `people.txt` в той же директории, что и наш Nim код.
Содержимое этого файла выглядит так:

[source]
.people.txt
----
include::{source-dir}/people.txt[]

----

Мы хотим использовать содержимое этого файла в нашей программе, как список (последовательность) имён.

[source]
.readFromFile.nim
----
include::{source-dir}/readFromFile.nim[]
----
<1> Чтобы прочитать содержимое файла, мы используем процедуру `readFile`, и передаем ей путь к файлу, из которого нужно читать (если файл находится в той же директории, что и наш Nim-программа, достаточно просто указать имя файла). Результатом является многострочная строка.
<2> Чтобы разбить многострочную строку на последовательность строк (каждая строка содержит содержимое одной строки файла), мы используем `splitLines` из модуля `strutils`.

[source, output]
----
Alice A.
Bob B.
Carol C.
            <1>
@["Alice A.", "Bob B.", "Carol C.", ""] <2>
----
<1> Это последняя строка в файле, которая содержит пустую строку.
<2> Из-за пустой строки в конце файла, наша последовательность длиннее, чем мы ожидали/хотели.

Чтобы решить проблему с пустой строкой в конце, мы можем использовать процедуру `strip` из модуля `strutils` после чтения файла.
Всё, что делает `strip`, это удаляет любые так называемые пробельные символы (whitespace) в начале и конце строки.
Пробельные символы — это просто символы, создающие пробелы: новые строки, пробелы, табуляции и т.д.
[source]
.readFromFile2.nim
----
include::{source-dir}/readFromFile2.nim[]
----
<1> Используя `strip`, мы получаем ожидаемые результаты.

[source, output]
----
Alice A.
Bob B.
Carol C.
@["Alice A.", "Bob B.", "Carol C."]
----




== Чтение пользовательского ввода

Если мы хотим взаимодействовать с пользователем, мы должны иметь возможность запрашивать у него ввод, а затем обрабатывать его и использовать.
Нам нужно читать из https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)[стандартного ввода (stdin)] передавая `stdin` в процедуру `readLine`.

[source]
.interaction1.nim
----
include::{source-dir}/interaction1.nim[]
----
<1> Тип `name` автоматически определяется как строка.


[source, output]
----
Please enter your name:
        <1>
----
<1> Ожидаем ввод от пользователя. После того как мы введем имя и нажмем `Enter`, программа продолжится.

[source, output]
----
Please enter your name:
Alice
Hello Alice, nice to meet you!
----

NOTE: Если вы используете устаревшую версию VS Code, вы не можете запускать это обычным способом (используя `Ctrl+Alt+N`), потому что окно вывода не позволяет вводить данные пользователя -- вам нужно запускать эти примеры в терминале. +
С более новыми версиями VS Code такой проблемы нет.




== Работа с числами

Чтение из файла или из пользовательского ввода всегда даёт строку в качестве результата.
Если мы хотим использовать числа, нам нужно конвертировать строки в числа: мы снова используем модуль `strutils` и используем `parseInt` для конвертации в целые числа или `parseFloat` для конвертации в число с плавающей точкой.

[source]
.interaction2.nim
----
include::{source-dir}/interaction2.nim[]
----
<1> Конвертируем строку в целое число. Когда написано так, мы доверяем пользователю, что он введёт корректное целое число. Что произойдёт, если пользователь введёт `'79` или `ninety-three`? Попробуйте сами.

[source, output]
----
Please enter your year of birth:
1934
You are 84 years old.
----

{nbsp}

Допустим, у нас есть файл `numbers.txt` в той же директории, что и наш Nim код, со следующим содержимым:

[source]
.numbers.txt
----
include::{source-dir}/numbers.txt[]
----

и мы хотим прочитать этот файл и найти сумму и среднее значение предоставленных чисел, мы можем сделать следующее:

[source]
.interaction3.nim
----
include::{source-dir}/interaction3.nim[]
----
<1> Мы импортируем несколько модулей. `strutils` даёт нам `strip` и `splitLines`, `sequtils` даёт `map`, а `math` даёт `sum`.
<2> Мы удаляем последнюю новую строку, и разбиваем строки на последовательность строк.
<3> `map` работает, применяя процедуру (в данном случае `parseFloat`) к каждому элементу контейнера. Другими словами, мы конвертируем каждую строку в число с плавающей точкой, возвращая новую последовательность чисел с плавающей точкой.
<4> Используем `sum` из модуля `math`, чтобы получить сумму всех элементов в последовательности.
<5> Нам нужно конвертировать длину последовательности в число с плавающей точкой, потому что `sumNums` является числом с плавающей точкой.
[source, output]
----
226.15
45.23
----




== Упражнения 

1. Спросите пользователя о его росте и весе. Рассчитайте его https://en.wikipedia.org/wiki/Body_mass_index[ИМТ]. Сообщите пользователю значение ИМТ и категорию.

2. Повторите упражнение о гипотезе Коллатца, чтобы ваша программа запрашивала у пользователя начальное число. Выведите получившуюся последовательность.

3. Спросите пользователя о строке, которую он хочет перевернуть. Создайте процедуру, которая принимает строку и возвращает перевернутую версию. Например, если пользователь введет `Nim-lang`, процедура должна вернуть `gnal-miN`. (Подсказка: используйте индексацию и `countdown`)